# Generated by Django 4.2 on 2023-05-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrencies',
            name='logoImage',
            field=models.FileField(blank=True, null=True, upload_to='cryptocurrenciesLogo'),
        ),
        migrations.AlterField(
            model_name='personalprediction',
            name='predictedData',
            field=models.TextField(blank=True, null=True),
        ),
    ]
