# Generated by Django 4.2 on 2023-05-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_systemprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='prophetscore',
            name='machineLearningModel',
            field=models.FileField(null=True, upload_to='ProphetModel'),
        ),
        migrations.AlterField(
            model_name='lstmmodel',
            name='machineLearningModel',
            field=models.FileField(null=True, upload_to='LstmModel'),
        ),
    ]
