# Generated by Django 4.2 on 2023-05-15 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_prophetscore_machinelearningmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NHitsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('rmse', models.CharField(max_length=20)),
                ('mape', models.CharField(max_length=20)),
                ('machineLearningModel', models.FileField(null=True, upload_to='NHitsModel')),
                ('createDateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='ProphetScore',
            new_name='ProphetModel',
        ),
        migrations.AddField(
            model_name='cryptocurrencies',
            name='NhitsId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.nhitsmodel'),
        ),
    ]
