# Generated by Django 4.2 on 2023-05-16 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_nhitsmodel_rename_prophetscore_prophetmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptocurrencies',
            name='predictedData',
        ),
    ]
