# Generated by Django 4.2 on 2023-05-16 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_cryptocurrencies_predicteddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='lstmmodel',
            name='PredictedData',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nhitsmodel',
            name='predictedData',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prophetmodel',
            name='predictedData',
            field=models.TextField(blank=True, null=True),
        ),
    ]
