# Generated by Django 4.2 on 2023-05-16 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_lstmmodel_predicteddata_nhitsmodel_predicteddata_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptocurrencies',
            old_name='lstmModelId',
            new_name='lstmId',
        ),
    ]
