# Generated by Django 4.2 on 2023-05-17 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_lstmmodelid_cryptocurrencies_lstmid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lstmmodel',
            old_name='PredictedData',
            new_name='predictedData',
        ),
    ]
