# Generated by Django 4.2 on 2023-05-22 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_predicteddata_lstmmodel_predicteddata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptocurrencies',
            old_name='NhitsId',
            new_name='nhitsId',
        ),
    ]
